spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
        thread-name-prefix: my-task-executor-


server:
  port: 8085

logging:
  level:
    root: info

hash:
  batch: 10

executor:
  service:
    batch_size: 5

scheduler:
  cleaner: '@daily'

cache:
  capacity:
    value: 5
    min_percent: 0.2

controller:
  mapping:
    url_shortener: api/v1/url-shortener


task:
  execution:
    pool:
      name: taskExecutor