spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  data:
    redis:
      port: 6379
      host: localhost

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600


server:
  port: 8085

logging:
  level:
    root: info

hash:
  batch: 10

executor:
  service:
    batch_size: 5

scheduler:
  cleaner: '@daily'

cache:
  capacity:
    value: 5
    min_percent: 0.2
