spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    thread-name-prefix: UrlShortenerThread-

redis:
  host: localhost
  port: 6379
  channel_fo_cache:
      name: cache_channel

liquibase:
  change-log: classpath:db/changelog/changeset/db.changelog-master.yaml

server:
  port: 8080
  version: /api/v1
  shorter: https://sh.c/

scheduled:
  cron: "0 0 0 * * ?"


logging:
  level:
    root: info